# Generated by Django 6.0.2 on 2026-02-20 22:55

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('author', models.CharField(default='soroush osivand', max_length=150)),
                ('author_href', models.URLField(blank=True, default='#', max_length=500)),
                ('color', models.CharField(choices=[('#2563EB', 'Blue'), ('#F97316', 'Orange')], default='#2563EB', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.blog_image_path)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Short excerpt for blog cards (auto-generated from content if blank)')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
